services:
  postgres:
    image: postgres:17
    container_name: room-poll-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: pulse_rooms_db
      POSTGRES_USER: pulse_user
      POSTGRES_PASSWORD: room_password_db

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: